### ISSUE TITLE
Clojurescript support

### ISSUE THREAD

**Issue by bsteuber** [gfredericks/seventy-one#11]
Would be nice to use this in cljs projects too..

**Comment by gfredericks** [comment]
I wonder if `mv seventy_one.clj seventy_one.cljc` would accomplish this. Needs some research. I'm not opposed in any case.

**Comment by hypirion** [comment]
I think technomancy/leiningen#1827 must be resolved before this is possible.

**Comment by atroche** [comment]
any update on this?

**Comment by gfredericks** [comment]
I just released `0.1.1` which now uses a `.cljc` file and so should be clojurescript-compatible.
